services:
  bot:
    image: ghcr.io/the-a-p-o-l-l-o-organization/taiscatimebot:latest
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: apollo-interlink
